#! /bin/sh
case "$1" in
	start)
		sleep 5
		udhcpc
		mkdir /mnt/sdcard >> /var/log.log
		mount /dev/mmcblk0p1 /mnt/sdcard >> /var/log.log ;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}" ;;
esac
