#!/bin/sh

KEY_1=10
KEY_2=22
KEY_3=27

LED_1=23
LED_2=18
LED_3=17
LED_4=24

gpio_direction_output $LED_1 1
gpio_direction_output $LED_2 1
gpio_direction_output $LED_3 1
gpio_direction_output $LED_4 1

gpio_set_value $LED_1 0
gpio_set_value $LED_2 0
gpio_set_value $LED_3 0
gpio_set_value $LED_4 0

timeToAutoboot=10
clicked=0
while [ $clicked -eq 0 ]; do
	sleep 1
	let timeToAutoboot=timeToAutoboot-1
	if [ $timeToAutoboot -eq 0 ]; then
		clicked=$KEY_2
		echo "Default system (user) will be booted"
		sleep 1
	else
		echo "Time left to auto boot: " $timeToAutoboot
	fi
	
	for i in $KEY_1 $KEY_2 $KEY_3 ; do
		gpio_get_value $i
		if [ $? -eq 0 ]; then
			clicked=$i
		fi
		if [ $clicked -ne 0 ]; then
			if [ $clicked -eq $KEY_1 ]; then
				gpio_set_value $LED_1 1
				echo "Booting administrator system on initramfs"
				bootm /boot/adm_uImage
				exit 0
			elif [ $clicked -eq $KEY_2 ]; then
				gpio_set_value $LED_4 1
				echo "Booting user system on e2fs"
				mkdir /boot2
				mount /dev/disk0.1 /boot2
				bootm /boot2/boot/uImage
				exit 0
			else
				echo "Opening Barebox"
				gpio_set_value $LED_1 1
				gpio_set_value $LED_2 1
				gpio_set_value $LED_3 1
				gpio_set_value $LED_4 1
				exit 0
			fi
		fi
	done
done
